---
- name: Create GPG keypair
  script: templates/gpg.sh.j2
  become: yes
  become_user: "{{ user | default(ansible_user) }}"
  when:
    - duplicity_backup_create_gpg_keypair is defined
    - duplicity_backup_create_gpg_keypair == "True"
  no_log: True # includes secrets
  tags: duplicity_backup_create_gpg_keypair

- name: Create duplicity directory
  file:
    path: "{{ duplicity_basepath | default(ansible_env.PWD) }}/.duplicity"
    state: directory
    owner: "{{ user | default(ansible_user) }}"
    group: "{{ user | default(ansible_user) }}"
    mode: '0700'
  tags: duplicity_backup_define_environment_variables

- name: Define environment variables
  template:
    src: env_variables.conf.j2
    dest: "{{ duplicity_basepath | default(ansible_env.PWD) }}/.duplicity/.env_variables.conf"
    owner: "{{ user | default(ansible_user) }}"
    group: "{{ user | default(ansible_user) }}"
    mode: '0600'
  no_log: True # includes secrets
  tags: duplicity_backup_define_environment_variables

- name: Create log directory
  file:
    path: /var/log/duplicity
    state: directory
    owner: "{{ user | default(ansible_user) }}"
    group: "{{ user | default(ansible_user) }}"
    mode: '0700'
  tags: duplicity_backup_create_log_directory

- name: Deploy backup script according to user configuration
  block:
  - name: Include vars
    include_vars: user_config.yml

  - name: Deploy backup script
    template:
      src: backup.sh.j2
      dest: "{{ duplicity_basepath | default(ansible_env.PWD) }}/.duplicity/.backup.sh"
      owner: "{{ user | default(ansible_user) }}"
      group: "{{ user | default(ansible_user) }}"
      mode: '0700'
  tags: duplicity_backup_deploy_backup_script
...
