---
dependency:
  name: galaxy
  options:
    role-file: meta/requirements.yml
driver:
  name: docker
lint: |
  set -e
  ansible-lint .
  yamllint .
  flake8 .
platforms:
  - name: debian_buster
    ansible_groups:
      - root
    image: debian:10
    privileged: true
    pre_build_image: false
provisioner:
  name: ansible
  inventory:
    group_vars:
      all:
        ansible_python_interpreter: /usr/bin/python3
        ansible_user: root
        duplicity_basepath: /root
        gpg_key_path: "{{ role_path }}/files/gnupg"
  env:
    DPBX_ACCESS_TOKEN: test_token
    DPBX_APP_KEY: test_key
    DPBX_APP_SECRET: test_secret
    PASSPHRASE: test_passphrase
verifier:
  name: testinfra
...
